{{- if .Values.catalog.podDisruptionBudget.enabled }}
apiVersion: {{ .Values.catalog.podDisruptionBudget.apiVersion }}
kind: PodDisruptionBudget
metadata:
  name: {{ include "iceberg-catalog.fullname" . }}
  labels:
    {{- include "iceberg-catalog.labels" . | nindent 4 }}
    component: catalog
spec:
  {{- if .Values.catalog.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.catalog.podDisruptionBudget.maxUnavailable }}
  {{- end }}
  {{- if .Values.catalog.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.catalog.podDisruptionBudget.minAvailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "iceberg-catalog.selectorLabels" . | nindent 6 }}
      component: catalog
{{- end }}
